// Code generated by glaciergen; DO NOT EDIT.

package ghreleases

import (
	"context"
	"github.com/nathanbrophy/glacier/mock"
)

// ReleaseFetcherMock is a generated typed mock for the ReleaseFetcher interface.
// Use On<MethodName>(...) to register expectations.
type ReleaseFetcherMock struct {
	mock.Mock[ReleaseFetcher]
}

// OnLatest starts building an expectation for the "Latest" method.
func (w *ReleaseFetcherMock) OnLatest(m0 mock.Matcher[context.Context], m1 mock.Matcher[string]) *ReleaseFetcherMockExpectation_Latest {
	e := w.OnCall("Latest").With(m0, m1)
	return &ReleaseFetcherMockExpectation_Latest{Expectation: e}
}

// ReleaseFetcherMockExpectation_Latest is the typed expectation builder for the "Latest" method.
type ReleaseFetcherMockExpectation_Latest struct{ *mock.Expectation }

// Return sets the fixed return values for this expectation.
func (e *ReleaseFetcherMockExpectation_Latest) Return(r0 Release, r1 error) *ReleaseFetcherMockExpectation_Latest {
	e.Expectation.Return(r0, r1)
	return e
}
