//go:build glacier_codegen_fixture

// Code generated by glaciergen. DO NOT EDIT.
// Source: in.go
package apiclient

import (
	"net/http"

	"github.com/nathanbrophy/glacier/httpmock"
)

// MockStrictTransport is a generated httpmock-backed transport for StrictTransport.
// Recording is disabled: unregistered requests return an error immediately.
type MockStrictTransport struct {
	router *httpmock.Router
}

// NewMockStrictTransport returns a MockStrictTransport with recording disabled.
// Any request that does not match a registered route will return an error.
func NewMockStrictTransport() *MockStrictTransport {
	return &MockStrictTransport{
		router: httpmock.NewRouter(httpmock.WithRecordingDisabled()),
	}
}

// Route registers a handler for the given method and path pattern.
func (m *MockStrictTransport) Route(method, path string, handler httpmock.Handler) {
	m.router.Route(method, path, handler)
}

// RoundTrip implements StrictTransport (and http.RoundTripper).
func (m *MockStrictTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	return m.router.RoundTrip(req)
}
