//go:build glacier_codegen_fixture

// Code generated by glaciergen. DO NOT EDIT.
// Source: in.go
package client

import (
	"context"
	"net/http"
)

// MockHTTPClient is a generated mock for HTTPClient.
type MockHTTPClient struct {
	// OnDo is called by Do. Set this in your test to control behavior.
	OnDo func(ctx context.Context, req *http.Request) (*http.Response, error)
}

// Do implements HTTPClient.
func (m *MockHTTPClient) Do(ctx context.Context, req *http.Request) (*http.Response, error) {
	return m.OnDo(ctx, req)
}
