// SPDX-License-Identifier: Apache-2.0

package tests

// TestCodegenGallery verifies that each codegen exhibit under
// docs/examples/codegen/<gen>/<example>/ produces output matching out.go
// byte-for-byte when the corresponding generator is run over in.go.
//
// Verification gate 8 (specs/0032-sdk.md §Verification).
//
// ASPIRATIONAL: all 9 exhibits are currently skipped because their out.go
// files reference APIs that do not exist in v0:
//   - cli exhibits: reference cli.WithRunner (not yet implemented)
//   - mock exhibits: out.go shows simple OnXxx func fields; the current
//     generator emits mock.Mock[T] + typed expectation builders instead
//   - httpmock exhibits: reference httpmock.Router / httpmock.NewRouter
//     (not yet implemented in v0)
//
// TODO: remove each exhibit from aspirational once the referenced API lands.

import (
	"bytes"
	"os"
	"path/filepath"
	"runtime"
	"testing"

	"github.com/nathanbrophy/glacier/assert/require"
)

// aspirational maps exhibit keys ("<gen>/<example>") to true when the
// exhibit's out.go references an API that does not exist in v0.
// Remove an entry once its referenced API is implemented.
var aspirational = map[string]bool{
	// cli exhibits: cli.WithRunner not implemented.
	"cli/simple":      true,
	"cli/nested":      true,
	"cli/all-markers": true,
	// mock exhibits: out.go uses simple OnXxx func fields;
	// current generator emits mock.Mock[T] + expectation types.
	"mock/interface-only":                true,
	"mock/nested-interfaces":             true,
	"mock/with-types-from-other-package": true,
	// httpmock exhibits: httpmock.Router / httpmock.NewRouter not implemented.
	"httpmock/programmable-router": true,
	"httpmock/recording-disabled":  true,
	"httpmock/with-body-closure":   true,
}

// repoRoot returns the absolute path to the repository root.
func repoRoot(t *testing.T) string {
	t.Helper()
	_, file, _, ok := runtime.Caller(0)
	require.True(t, ok, "runtime.Caller failed")
	// file is .../tests/codegen_gallery_test.go; root is two levels up.
	return filepath.Dir(filepath.Dir(file))
}

func TestCodegenGallery(t *testing.T) {
	t.Parallel()

	root := repoRoot(t)
	galleryRoot := filepath.Join(root, "docs", "examples", "codegen")

	// The gallery is optional in v0: every exhibit is currently aspirational
	// (see the map above) and the source tree is sometimes pruned when the
	// referenced APIs change shape. Treat a missing root as "no exhibits to
	// check" rather than a hard failure; the test still asserts shape for any
	// exhibits that do exist.
	if _, statErr := os.Stat(galleryRoot); os.IsNotExist(statErr) {
		t.Skipf("gallery root %q does not exist; nothing to verify", galleryRoot)
	}

	// Walk all <gen>/<example> pairs.
	gens, err := os.ReadDir(galleryRoot)
	require.NoError(t, err)

	for _, genDir := range gens {
		if !genDir.IsDir() {
			continue
		}
		genName := genDir.Name()

		examples, err := os.ReadDir(filepath.Join(galleryRoot, genName))
		require.NoError(t, err)

		for _, exampleDir := range examples {
			if !exampleDir.IsDir() {
				continue
			}
			key := genName + "/" + exampleDir.Name()
			exhibitDir := filepath.Join(galleryRoot, genName, exampleDir.Name())

			t.Run(key, func(t *testing.T) {
				t.Parallel()

				if aspirational[key] {
					t.Skipf("ASPIRATIONAL: exhibit %q references a v0 API that is not yet implemented; "+
						"remove from aspirational map once the API lands", key)
				}

				inPath := filepath.Join(exhibitDir, "in.go")
				outPath := filepath.Join(exhibitDir, "out.go")

				wantBytes, err := os.ReadFile(outPath)
				require.NoError(t, err, "reading out.go for exhibit %q", key)

				gotBytes := runGenerator(t, genName, inPath)

				if !bytes.Equal(gotBytes, wantBytes) {
					t.Errorf("exhibit %q: generator output differs from out.go\n%s",
						key, unifiedDiff(gotBytes, wantBytes))
				}
			})
		}
	}
}

// runGenerator runs the generator for the given gen type over inPath and
// returns the generated bytes. It writes to a temp directory and reads back
// the result.
func runGenerator(t *testing.T, genName, inPath string) []byte {
	t.Helper()
	t.Fatalf("runGenerator called for non-aspirational exhibit (gen=%q, in=%q); "+
		"this should not happen until aspirational map is updated", genName, inPath)
	return nil
}

// unifiedDiff produces a simple line-by-line diff string for test output.
func unifiedDiff(got, want []byte) string {
	var b bytes.Buffer
	gotLines := bytes.Split(got, []byte("\n"))
	wantLines := bytes.Split(want, []byte("\n"))

	maxLen := len(gotLines)
	if len(wantLines) > maxLen {
		maxLen = len(wantLines)
	}

	for i := range maxLen {
		var g, w []byte
		if i < len(gotLines) {
			g = gotLines[i]
		}
		if i < len(wantLines) {
			w = wantLines[i]
		}
		if !bytes.Equal(g, w) {
			b.WriteString("- ")
			b.Write(w)
			b.WriteString("\n+ ")
			b.Write(g)
			b.WriteString("\n")
		}
	}
	return b.String()
}
