//go:build glacier_codegen_fixture

// Code generated by glaciergen. DO NOT EDIT.
// Source: in.go
package main

import (
	"github.com/nathanbrophy/glacier/cli"
)

func init() {
	cli.Default.Register(
		cli.WithName("myapp"),
		cli.WithRoot(),
		cli.WithRunner(func() cli.Runner { return &MyApp{} }),
	)
	cli.Default.Register(
		cli.WithName("deploy"),
		cli.WithParent("myapp"),
		cli.WithRunner(func() cli.Runner { return &DeployCmd{} }),
		cli.WithFlagRequired("Env"),
		cli.WithFlagChoices("Env", []string{"staging", "production"}),
		cli.WithFlagShort("Env", 'e'),
		cli.WithFlagEnv("Env", "DEPLOY_ENV"),
		cli.WithFlagDefault("Parallel", 2),
		cli.WithFlagDefault("DryRun", false),
		cli.WithFlagChoices("Strategy", []string{"rolling", "blue-green", "canary"}),
		cli.WithFlagDefault("Strategy", "rolling"),
		cli.WithFlagValidate("Strategy", validateStrategy),
		cli.WithFlagDeprecated("OldFlag", "Use --strategy instead."),
		cli.WithPositional("Target"),
	)
}
