// SPDX-License-Identifier: Apache-2.0

package cli

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"io"
	"log/slog"
	"os"
	"reflect"
	"runtime"
	"strings"
	"sync"

	"github.com/nathanbrophy/glacier/option"
)

// appConfig holds the options accumulated for a New call.
type appConfig struct {
	version  string
	stdout   io.Writer
	stderr   io.Writer
	logger   *slog.Logger
	noBanner bool // WithoutBanner sets this; banner is on by default
}

// regConfig holds the options accumulated for a single Register call.
type regConfig struct {
	name       string
	parent     string
	aliases    []string
	short      map[string]rune
	envVars    map[string]string
	help       map[string]string
	root       bool
	deprecated map[string]string
	required   map[string]struct{}
	choices    map[string][]string
	validate   map[string]func(string) error

	// summary is a one-line description of the command shown in the
	// top-level help listing. Empty when WithSummary was not provided.
	summary string
	// category groups commands in the top-level help (e.g. "create", "develop",
	// "inspect", "utility"). Empty falls back to "other".
	category string
	// longDesc is a multi-line description shown below the synopsis on
	// per-command help pages. Empty when WithLongDescription was not provided.
	longDesc string
}

// entry is an internal command registration record.
type entry struct {
	cmd  command
	cfg  regConfig
	path string
}

// App is the central registry and dispatcher.
// App is goroutine-safe after construction; all exported methods are safe to
// call concurrently except Close, which must be called at most once concurrently
// (subsequent concurrent Close calls return nil safely via sync.Once).
type App struct {
	mu        sync.RWMutex
	cfg       appConfig
	commands  map[string]*entry // keyed by dot-separated path
	aliases   map[string]string // alias → canonical path
	closeOnce sync.Once
	closed    chan struct{}
	rootPath  string // canonical path of the root command (if registered)

	// lastFlags holds the flag values from the most recent Run call.
	// Protected by mu.
	lastFlags map[string]string
}

// Default is the package-level App used by generated code.
// Code generated by glaciergen calls Register on Default.
// Tests must not leak registrations; use a separate App constructed with New().
var Default = New()

// New constructs an App with the supplied options applied.
// The banner is shown by default (§23.15); suppress with WithoutBanner().
func New(opts ...option.Option[appConfig]) *App {
	cfg, err := option.Apply(opts)
	if err != nil {
		// Option errors in New are programmer errors; panic to surface immediately.
		//glacier:nolint=panic-in-library programmer error: option misuse surfaces at App construction.
		panic("cli: New: " + err.Error())
	}
	// Apply defaults for zero-valued fields.
	if cfg.stdout == nil {
		cfg.stdout = os.Stdout
	}
	if cfg.stderr == nil {
		cfg.stderr = os.Stderr
	}
	if cfg.logger == nil {
		cfg.logger = slog.Default()
	}
	return &App{
		cfg:      cfg,
		commands: make(map[string]*entry),
		aliases:  make(map[string]string),
		closed:   make(chan struct{}),
	}
}

// Register adds cmd to the App's command registry.
//
// cmd must have method Run(ctx context.Context) error; any other type causes a
// registration error. opts configure the command's name, parent path, aliases,
// flag metadata, and root status.
//
// Register is goroutine-safe.
func (a *App) Register(cmd any, opts ...option.Option[regConfig]) error {
	// Verify cmd implements Run(ctx context.Context) error.
	if err := checkCommand(cmd); err != nil {
		return err
	}

	cfg, err := option.Apply(opts)
	if err != nil {
		return fmt.Errorf("cli: Register: option error: %w", err)
	}

	// Derive name from type if not set.
	if cfg.name == "" {
		cfg.name = deriveName(cmd)
	}

	// Determine the full dot-separated path.
	var path string
	if cfg.parent != "" {
		path = cfg.parent + "." + cfg.name
	} else {
		path = cfg.name
	}

	a.mu.Lock()
	defer a.mu.Unlock()

	// Check for duplicate path.
	if _, exists := a.commands[path]; exists {
		return fmt.Errorf("cli: Register: duplicate command path %q", path)
	}

	// Check for multiple roots.
	if cfg.root {
		if a.rootPath != "" {
			return &ErrMultipleRoots{First: a.rootPath, Second: path}
		}
		a.rootPath = path
	}

	// Verify parent exists (if specified).
	if cfg.parent != "" {
		if _, ok := a.commands[cfg.parent]; !ok {
			return &ErrUnresolvedParent{Child: path, Parent: cfg.parent}
		}
	}

	// Register aliases.
	for _, alias := range cfg.aliases {
		a.aliases[alias] = path
	}

	// Wrap cmd as command interface.
	c := cmd.(command)

	a.commands[path] = &entry{
		cmd:  c,
		cfg:  cfg,
		path: path,
	}
	return nil
}

// Run dispatches argv to the matching command and calls its Run(ctx) method.
//
// argv is the raw argument slice (typically os.Args[1:]).
// The first element(s) that do not begin with "-" form the command path.
// Subcommand depth is unlimited.
//
// Signal handling: Run installs SIGINT/SIGTERM (Unix) or os.Interrupt (Windows)
// cancellation on ctx. The first signal cancels the derived context.
//
// Error contract: returns *ErrUnknownCommand, *ErrUnknownFlag, *FlagParseError,
// ErrCancelled, *ErrPanic, or the handler's error verbatim.
func (a *App) Run(ctx context.Context, argv []string) (retErr error) {
	if ctx.Err() != nil {
		return ErrCancelled
	}

	// Validate argv elements.
	for _, arg := range argv {
		if len(arg) > 64*1024 {
			return &FlagParseError{Name: arg[:32] + "...", Err: fmt.Errorf("argument exceeds 64 KiB")}
		}
		if strings.ContainsRune(arg, '\x00') {
			return &FlagParseError{Name: arg, Err: fmt.Errorf("argument contains NUL byte")}
		}
	}

	// Persistent root flags (D-S33): peel any token in argv that names a
	// flag declared on the root command's struct, parse them into the root
	// instance, and remove them from argv before subcommand resolution.
	// Without this step, `glacier --verbose test` would dispatch to the
	// root command (because splitArgv stops at the first '-'), and
	// `glacier test --verbose` would fail with ErrUnknownFlag because the
	// test subcommand's flag set doesn't declare --verbose.
	rootEntry := a.rootEntryLocked()
	var rootVals map[string]string
	if rootEntry != nil {
		peeled, remaining := peelRootFlags(argv, rootEntry)
		vals, err := parseRootFlags(rootEntry, peeled)
		if err != nil {
			return err
		}
		rootVals = vals
		argv = remaining
		if applier, ok := rootEntry.cmd.(RootApplier); ok {
			if err := applier.ApplyRoot(ctx); err != nil {
				return err
			}
		}
	}

	// Extract command path tokens (leading non-flag tokens).
	cmdTokens, rest := splitArgv(argv)

	// Resolve command path.
	e, resolvedPath := a.resolve(cmdTokens)
	if e == nil {
		return &ErrUnknownCommand{Path: resolvedPath}
	}

	// Build the flag set for this command.
	fs, _ := buildFlagSet(e.cmd, e.cfg, e.path)

	// Add automatic --help and --version flags.
	var helpFlag bool
	var versionFlag bool
	fs.BoolVar(&helpFlag, "help", false, "print usage and exit")
	fs.BoolVar(&helpFlag, "h", false, "print usage and exit (shorthand)")
	if e.cfg.root {
		fs.BoolVar(&versionFlag, "version", false, "print version and exit")
		fs.BoolVar(&versionFlag, "v", false, "print version and exit (shorthand)")
	}

	// Parse flags; capture unknown flag errors.
	if err := fs.Parse(rest); err != nil {
		if strings.HasPrefix(err.Error(), "flag provided but not defined: ") {
			name := strings.TrimPrefix(err.Error(), "flag provided but not defined: -")
			return &ErrUnknownFlag{Name: name}
		}
		return &FlagParseError{Name: "", Err: err}
	}

	if helpFlag {
		_ = a.Help(e.path)
		return nil
	}
	if versionFlag {
		a.Version()
		return nil
	}

	// Apply env var overrides.
	applyEnvOverrides(fs, e.cfg)

	// Log deprecated flag warnings.
	for flagName, msg := range e.cfg.deprecated {
		lower := fieldFlagName(flagName)
		f := fs.Lookup(lower)
		if f == nil {
			continue
		}
		// Check if the flag was set.
		set := false
		fs.Visit(func(ff *flag.Flag) {
			if ff.Name == lower {
				set = true
			}
		})
		if set {
			if msg != "" {
				a.cfg.logger.Warn("deprecated flag used", "flag", lower, "message", msg)
			} else {
				a.cfg.logger.Warn("deprecated flag used", "flag", lower)
			}
		}
	}

	// Validate required flags.
	if err := validateRequiredFlags(fs, e.cfg); err != nil {
		return err
	}

	// Validate choices.
	if err := validateChoices(fs, e.cfg); err != nil {
		return err
	}

	// Run per-flag validate functions.
	if err := validateFns(fs, e.cfg); err != nil {
		return err
	}

	// Store flag values for Lookup. Root persistent-flag values from the
	// peel-and-parse pass are seeded first so the active command's own
	// flags (if a name collides) win on the merge.
	vals := make(map[string]string, len(rootVals)+1)
	for k, v := range rootVals {
		vals[k] = v
	}
	for k, v := range flagValues(fs) {
		vals[k] = v
	}
	a.mu.Lock()
	a.lastFlags = vals
	a.mu.Unlock()

	// Install signal handling.
	sigCtx, sigStop := installSignals(ctx)
	defer sigStop()

	// Recover panics from the handler.
	defer func() {
		if r := recover(); r != nil {
			buf := make([]byte, 4096)
			n := runtime.Stack(buf, false)
			retErr = &ErrPanic{Value: r, Stack: buf[:n]}
		}
	}()

	return e.cmd.Run(sigCtx)
}

// Main calls Run with os.Args[1:] and, on a non-nil error, formats the error
// to stderr and calls os.Exit with a code derived from the error chain.
//
// Exit code resolution:
//   - nil error → exit 0
//   - error chain contains an ExitCoder (errors.As) → exit ExitCoder.ExitCode()
//   - any other error → exit 1
//
// On ErrUnknownCommand, Main also calls Help before exiting.
// Main never returns to the caller.
func (a *App) Main() {
	argv := os.Args[1:]

	// Show banner on bare invocation.
	if len(argv) == 0 && !a.cfg.noBanner {
		writeBanner(a.cfg.stdout)
	}

	err := a.Run(context.Background(), argv)
	if err == nil {
		os.Exit(0)
	}

	var unkCmd *ErrUnknownCommand
	if isErrUnknownCommand(err, &unkCmd) {
		_ = a.Help(unkCmd.Path)
	}

	fmt.Fprintf(a.cfg.stderr, "error: %s\n", err)

	// Honor any ExitCoder in the error chain.
	var coder ExitCoder
	if errors.As(err, &coder) {
		os.Exit(coder.ExitCode())
	}
	os.Exit(1)
}

// Annotate applies help-related options (WithSummary, WithCategory,
// WithLongDescription) to an already-registered command. Useful when the
// generator (cligen) does not yet emit these options at registration time;
// the SDK can attach metadata in a separate init() call.
//
// Annotate reads only the help fields (summary, category, longDesc) from
// the supplied options; identity fields (name, parent, root) cannot be
// changed post-registration.
//
// Returns *ErrUnknownCommand if path is not registered, or any error from
// option.Apply.
func (a *App) Annotate(path string, opts ...option.Option[regConfig]) error {
	a.mu.Lock()
	defer a.mu.Unlock()
	e, ok := a.commands[path]
	if !ok {
		return &ErrUnknownCommand{Path: path}
	}
	delta, err := option.Apply(opts)
	if err != nil {
		return err
	}
	if delta.summary != "" {
		e.cfg.summary = delta.summary
	}
	if delta.category != "" {
		e.cfg.category = delta.category
	}
	if delta.longDesc != "" {
		e.cfg.longDesc = delta.longDesc
	}
	return nil
}

// Help writes the usage page for the command identified by path to the App's
// configured stdout writer. If path is empty, the root command's usage is written.
// Returns nil if the command exists, *ErrUnknownCommand otherwise.
//
// The rendering is delegated to renderHelp in help.go, which produces a
// banner + grouped subcommands + global flags + footer page for the root
// command and a synopsis + flags + see-also page for each subcommand.
func (a *App) Help(path string) error {
	return a.renderHelp(a.cfg.stdout, path)
}

// Version writes the version string to stdout.
func (a *App) Version() {
	v := a.cfg.version
	if v == "" {
		v = readBuildVersion()
	}
	fmt.Fprintf(a.cfg.stdout, "%s\n", v)
}

// Banner writes the banner art to stdout. On a TTY the 24-bit ANSI gradient is
// used; on a non-TTY or when NO_COLOR / GLACIER_NO_COLOR is set, plain text is used.
func (a *App) Banner() {
	writeBanner(a.cfg.stdout)
}

// Lookup returns the string-serialized value of the named flag as set during
// the most recent Run call. Returns ("", false) for unknown names.
// Concurrency: goroutine-safe.
func (a *App) Lookup(name string) (string, bool) {
	a.mu.RLock()
	defer a.mu.RUnlock()
	if a.lastFlags == nil {
		return "", false
	}
	v, ok := a.lastFlags[strings.ToLower(name)]
	return v, ok
}

// Close shuts down the App: cancels any pending signal handlers and frees
// resources. Close is idempotent :  subsequent calls return nil.
// Concurrency: goroutine-safe.
func (a *App) Close() error {
	a.closeOnce.Do(func() {
		close(a.closed)
	})
	return nil
}

// resolve finds the entry for the given command tokens. It tries progressively
// longer paths until it finds a match. Returns the entry and the resolved path.
func (a *App) resolve(tokens []string) (*entry, string) {
	a.mu.RLock()
	defer a.mu.RUnlock()

	if len(tokens) == 0 {
		// Try root.
		if a.rootPath != "" {
			return a.commands[a.rootPath], a.rootPath
		}
		return nil, ""
	}

	// Try longest-first path match.
	for length := len(tokens); length > 0; length-- {
		path := strings.Join(tokens[:length], ".")
		if e, ok := a.commands[path]; ok {
			return e, path
		}
		// Try alias.
		if canonical, ok := a.aliases[path]; ok {
			if e, ok2 := a.commands[canonical]; ok2 {
				return e, canonical
			}
		}
	}

	return nil, strings.Join(tokens, ".")
}

// RootApplier is implemented by root commands that need to react to their
// own flag values before any subcommand executes. App.Run invokes ApplyRoot
// after the root command's persistent flags have been parsed (and env
// overrides applied) but before splitArgv resolves the active command.
//
// A non-nil return aborts dispatch with that error. Typical uses: validating
// mutually-exclusive global flags, updating a process-wide log level, or
// installing signal handlers gated by a flag.
type RootApplier interface {
	ApplyRoot(ctx context.Context) error
}

// rootEntryLocked returns the registered root entry, or nil if no command
// was registered with WithRoot. The returned *entry is shared with the
// registry; callers must not mutate cfg fields.
func (a *App) rootEntryLocked() *entry {
	a.mu.RLock()
	defer a.mu.RUnlock()
	if a.rootPath == "" {
		return nil
	}
	return a.commands[a.rootPath]
}

// peelRootFlags walks argv left-to-right and partitions every token into
// `peeled` (matched a root flag, plus its value if non-bool) or `remaining`
// (positional, unknown flag, or flag belonging to a subcommand). The double
// dash `--` terminates root flag peeling: it and every subsequent token
// pass through to remaining unchanged, matching stdlib flag.Parse semantics.
//
// Bool flags (those whose value implements interface{ IsBoolFlag() bool })
// are single-token; non-bool flags consume the following token as their
// value unless the `--name=value` form is used.
func peelRootFlags(argv []string, root *entry) (peeled, remaining []string) {
	rootFs, _ := buildFlagSet(root.cmd, root.cfg, root.path)
	bools := make(map[string]bool)
	known := make(map[string]bool)
	rootFs.VisitAll(func(f *flag.Flag) {
		known[f.Name] = true
		if bf, ok := f.Value.(interface{ IsBoolFlag() bool }); ok && bf.IsBoolFlag() {
			bools[f.Name] = true
		}
	})

	i := 0
	for i < len(argv) {
		a := argv[i]
		if a == "--" {
			remaining = append(remaining, argv[i:]...)
			return
		}
		if !strings.HasPrefix(a, "-") || a == "-" {
			remaining = append(remaining, a)
			i++
			continue
		}
		name := strings.TrimLeft(a, "-")
		hasInlineValue := false
		if eq := strings.Index(name, "="); eq >= 0 {
			name = name[:eq]
			hasInlineValue = true
		}
		if !known[name] {
			remaining = append(remaining, a)
			i++
			continue
		}
		peeled = append(peeled, a)
		i++
		if !bools[name] && !hasInlineValue && i < len(argv) {
			peeled = append(peeled, argv[i])
			i++
		}
	}
	return
}

// parseRootFlags builds a fresh flag set bound to root's struct, parses the
// peeled tokens into it, and applies env-var overrides. Returns the
// resulting flag values keyed by lower-case flag name (suitable for merging
// into App.lastFlags). Errors are wrapped in the same shape App.Run uses
// for subcommand parse failures so callers see consistent error types.
func parseRootFlags(root *entry, peeled []string) (map[string]string, error) {
	fs, _ := buildFlagSet(root.cmd, root.cfg, root.path)
	if err := fs.Parse(peeled); err != nil {
		if strings.HasPrefix(err.Error(), "flag provided but not defined: ") {
			name := strings.TrimPrefix(err.Error(), "flag provided but not defined: -")
			return nil, &ErrUnknownFlag{Name: name}
		}
		return nil, &FlagParseError{Name: "", Err: err}
	}
	applyEnvOverrides(fs, root.cfg)
	return flagValues(fs), nil
}

// splitArgv separates leading non-flag tokens (command path) from the rest.
func splitArgv(argv []string) (cmdTokens []string, rest []string) {
	for i, arg := range argv {
		if strings.HasPrefix(arg, "-") {
			return argv[:i], argv[i:]
		}
		cmdTokens = append(cmdTokens, arg)
		_ = i
	}
	return cmdTokens, nil
}

// checkCommand verifies that cmd has method Run(ctx context.Context) error.
func checkCommand(cmd any) error {
	if cmd == nil {
		return fmt.Errorf("cli: Register: cmd is nil")
	}
	rt := reflect.TypeOf(cmd)
	// Check for Run method on the concrete type or its pointer.
	m, ok := rt.MethodByName("Run")
	if !ok {
		return fmt.Errorf("cli: Register: type %T has no Run method", cmd)
	}
	// Run(ctx context.Context) error: method type is func(T, context.Context) error
	// (first param is receiver).
	mt := m.Type
	if mt.NumIn() != 2 || mt.NumOut() != 1 {
		return fmt.Errorf("cli: Register: Run method on %T has wrong signature", cmd)
	}
	ctxType := reflect.TypeOf((*context.Context)(nil)).Elem()
	errType := reflect.TypeOf((*error)(nil)).Elem()
	if !mt.In(1).Implements(ctxType) {
		return fmt.Errorf("cli: Register: Run first param on %T is not context.Context", cmd)
	}
	if !mt.Out(0).Implements(errType) {
		return fmt.Errorf("cli: Register: Run return on %T is not error", cmd)
	}
	return nil
}

// deriveName derives a command name from the type name: lowercase, strip
// trailing "Cmd" suffix.
func deriveName(cmd any) string {
	rt := reflect.TypeOf(cmd)
	if rt.Kind() == reflect.Ptr {
		rt = rt.Elem()
	}
	name := rt.Name()
	name = strings.TrimSuffix(name, "Cmd")
	return strings.ToLower(name)
}

// isErrUnknownCommand checks whether err is *ErrUnknownCommand via errors.As.
func isErrUnknownCommand(err error, target **ErrUnknownCommand) bool {
	var e *ErrUnknownCommand
	if asErrUnknownCommand(err, &e) {
		*target = e
		return true
	}
	return false
}

// asErrUnknownCommand is a type-assertion helper.
func asErrUnknownCommand(err error, target **ErrUnknownCommand) bool {
	e, ok := err.(*ErrUnknownCommand)
	if ok {
		*target = e
	}
	return ok
}
