//go:build glacier_codegen_fixture

// Code generated by glaciergen. DO NOT EDIT.
// Source: in.go
package apiclient

import (
	"net/http"

	"github.com/nathanbrophy/glacier/httpmock"
)

// MockTransport is a generated httpmock-backed transport for Transport.
type MockTransport struct {
	router *httpmock.Router
}

// NewMockTransport returns a MockTransport with an empty route table.
// Register routes with mock.Route before making requests.
func NewMockTransport() *MockTransport {
	return &MockTransport{router: httpmock.NewRouter()}
}

// Route registers a handler for the given method and path pattern.
func (m *MockTransport) Route(method, path string, handler httpmock.Handler) {
	m.router.Route(method, path, handler)
}

// RoundTrip implements Transport (and http.RoundTripper).
func (m *MockTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	return m.router.RoundTrip(req)
}
