//go:build glacier_codegen_fixture

// Code generated by glaciergen. DO NOT EDIT.
// Source: in.go
package rw

// MockReadWriter is a generated mock for ReadWriter.
type MockReadWriter struct {
	// OnRead is called by Read. Set this in your test to control behavior.
	OnRead func(p []byte) (n int, err error)

	// OnWrite is called by Write. Set this in your test to control behavior.
	OnWrite func(p []byte) (n int, err error)

	// OnClose is called by Close. Set this in your test to control behavior.
	OnClose func() error
}

// Read implements ReadWriter (via Reader).
func (m *MockReadWriter) Read(p []byte) (n int, err error) {
	return m.OnRead(p)
}

// Write implements ReadWriter.
func (m *MockReadWriter) Write(p []byte) (n int, err error) {
	return m.OnWrite(p)
}

// Close implements ReadWriter.
func (m *MockReadWriter) Close() error {
	return m.OnClose()
}
