// Code generated by glaciergen; DO NOT EDIT.

package explaingen

import (
	"github.com/nathanbrophy/glacier/mock"
)

// SpecSourceMock is a generated typed mock for the SpecSource interface.
// Use On<MethodName>(...) to register expectations.
type SpecSourceMock struct {
	mock.Mock[SpecSource]
}

// OnConfigKeys starts building an expectation for the "ConfigKeys" method.
func (w *SpecSourceMock) OnConfigKeys() *SpecSourceMockExpectation_ConfigKeys {
	e := w.OnCall("ConfigKeys")
	return &SpecSourceMockExpectation_ConfigKeys{Expectation: e}
}

// SpecSourceMockExpectation_ConfigKeys is the typed expectation builder for the "ConfigKeys" method.
type SpecSourceMockExpectation_ConfigKeys struct{ *mock.Expectation }

// Return sets the fixed return values for this expectation.
func (e *SpecSourceMockExpectation_ConfigKeys) Return(r0 []ConfigKeyRow, r1 error) *SpecSourceMockExpectation_ConfigKeys {
	e.Expectation.Return(r0, r1)
	return e
}

// OnExitCodes starts building an expectation for the "ExitCodes" method.
func (w *SpecSourceMock) OnExitCodes() *SpecSourceMockExpectation_ExitCodes {
	e := w.OnCall("ExitCodes")
	return &SpecSourceMockExpectation_ExitCodes{Expectation: e}
}

// SpecSourceMockExpectation_ExitCodes is the typed expectation builder for the "ExitCodes" method.
type SpecSourceMockExpectation_ExitCodes struct{ *mock.Expectation }

// Return sets the fixed return values for this expectation.
func (e *SpecSourceMockExpectation_ExitCodes) Return(r0 []ExitCodeRow, r1 error) *SpecSourceMockExpectation_ExitCodes {
	e.Expectation.Return(r0, r1)
	return e
}

// OnMarkers starts building an expectation for the "Markers" method.
func (w *SpecSourceMock) OnMarkers() *SpecSourceMockExpectation_Markers {
	e := w.OnCall("Markers")
	return &SpecSourceMockExpectation_Markers{Expectation: e}
}

// SpecSourceMockExpectation_Markers is the typed expectation builder for the "Markers" method.
type SpecSourceMockExpectation_Markers struct{ *mock.Expectation }

// Return sets the fixed return values for this expectation.
func (e *SpecSourceMockExpectation_Markers) Return(r0 []MarkerRow, r1 error) *SpecSourceMockExpectation_Markers {
	e.Expectation.Return(r0, r1)
	return e
}
