//go:build glacier_codegen_fixture

// Code generated by glaciergen. DO NOT EDIT.
// Source: in.go
package main

import (
	"github.com/nathanbrophy/glacier/cli"
)

func init() {
	cli.Default.Register(
		cli.WithName("myapp"),
		cli.WithRoot(),
		cli.WithRunner(func() cli.Runner { return &MyApp{} }),
	)
	cli.Default.Register(
		cli.WithName("start"),
		cli.WithParent("myapp"),
		cli.WithRunner(func() cli.Runner { return &StartCmd{} }),
		cli.WithFlagDefault("Port", 8080),
		cli.WithFlagShort("Port", 's'),
	)
	cli.Default.Register(
		cli.WithName("stop"),
		cli.WithParent("myapp"),
		cli.WithRunner(func() cli.Runner { return &StopCmd{} }),
		cli.WithFlagDefault("Timeout", 30),
	)
}