//go:build glacier_codegen_fixture

// Code generated by glaciergen. DO NOT EDIT.
// Source: in.go
package apiclient

import (
	"io"
	"net/http"

	"github.com/nathanbrophy/glacier/httpmock"
)

// MockDynamicTransport is a generated httpmock-backed transport for DynamicTransport.
// Routes support a BodyFunc closure for per-request response body generation.
type MockDynamicTransport struct {
	router *httpmock.Router
}

// NewMockDynamicTransport returns a MockDynamicTransport with an empty route table.
func NewMockDynamicTransport() *MockDynamicTransport {
	return &MockDynamicTransport{router: httpmock.NewRouter()}
}

// Route registers a handler for the given method and path pattern.
func (m *MockDynamicTransport) Route(method, path string, handler httpmock.Handler) {
	m.router.Route(method, path, handler)
}

// RouteFunc registers a handler whose body is produced by a closure on each call.
// The closure receives the matched *http.Request and returns an io.Reader.
func (m *MockDynamicTransport) RouteFunc(method, path string, status int, bodyFn func(*http.Request) io.Reader) {
	m.router.RouteFunc(method, path, status, bodyFn)
}

// RoundTrip implements DynamicTransport (and http.RoundTripper).
func (m *MockDynamicTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	return m.router.RoundTrip(req)
}
