//go:build glacier_codegen_fixture

// Code generated by glaciergen. DO NOT EDIT.
// Source: in.go
package store

import "context"

// MockStore is a generated mock for Store.
type MockStore struct {
	// OnGet is called by Get. Set this in your test to control behavior.
	OnGet func(ctx context.Context, id string) (string, error)

	// OnPut is called by Put. Set this in your test to control behavior.
	OnPut func(ctx context.Context, id string, value string) error
}

// Get implements Store.
func (m *MockStore) Get(ctx context.Context, id string) (string, error) {
	return m.OnGet(ctx, id)
}

// Put implements Store.
func (m *MockStore) Put(ctx context.Context, id string, value string) error {
	return m.OnPut(ctx, id, value)
}