// Code generated by glaciergen; DO NOT EDIT.

package commands

import (
	"context"
	"github.com/nathanbrophy/glacier/mock"
)

// LinterMock is a generated typed mock for the Linter interface.
// Use On<MethodName>(...) to register expectations.
type LinterMock struct {
	mock.Mock[Linter]
}

// OnCheck starts building an expectation for the "Check" method.
func (w *LinterMock) OnCheck(m0 mock.Matcher[string], m1 mock.Matcher[[]byte]) *LinterMockExpectation_Check {
	e := w.OnCall("Check").With(m0, m1)
	return &LinterMockExpectation_Check{Expectation: e}
}

// LinterMockExpectation_Check is the typed expectation builder for the "Check" method.
type LinterMockExpectation_Check struct{ *mock.Expectation }

// Return sets the fixed return values for this expectation.
func (e *LinterMockExpectation_Check) Return(r0 []Finding) *LinterMockExpectation_Check {
	e.Expectation.Return(r0)
	return e
}

// OnName starts building an expectation for the "Name" method.
func (w *LinterMock) OnName() *LinterMockExpectation_Name {
	e := w.OnCall("Name")
	return &LinterMockExpectation_Name{Expectation: e}
}

// LinterMockExpectation_Name is the typed expectation builder for the "Name" method.
type LinterMockExpectation_Name struct{ *mock.Expectation }

// Return sets the fixed return values for this expectation.
func (e *LinterMockExpectation_Name) Return(r0 string) *LinterMockExpectation_Name {
	e.Expectation.Return(r0)
	return e
}

// OnSeverity starts building an expectation for the "Severity" method.
func (w *LinterMock) OnSeverity() *LinterMockExpectation_Severity {
	e := w.OnCall("Severity")
	return &LinterMockExpectation_Severity{Expectation: e}
}

// LinterMockExpectation_Severity is the typed expectation builder for the "Severity" method.
type LinterMockExpectation_Severity struct{ *mock.Expectation }

// Return sets the fixed return values for this expectation.
func (e *LinterMockExpectation_Severity) Return(r0 Severity) *LinterMockExpectation_Severity {
	e.Expectation.Return(r0)
	return e
}

// TestRunnerMock is a generated typed mock for the TestRunner interface.
// Use On<MethodName>(...) to register expectations.
type TestRunnerMock struct {
	mock.Mock[TestRunner]
}

// OnRun starts building an expectation for the "Run" method.
func (w *TestRunnerMock) OnRun(m0 mock.Matcher[context.Context], m1 mock.Matcher[[]string]) *TestRunnerMockExpectation_Run {
	e := w.OnCall("Run").With(m0, m1)
	return &TestRunnerMockExpectation_Run{Expectation: e}
}

// TestRunnerMockExpectation_Run is the typed expectation builder for the "Run" method.
type TestRunnerMockExpectation_Run struct{ *mock.Expectation }

// Return sets the fixed return values for this expectation.
func (e *TestRunnerMockExpectation_Run) Return(r0 <-chan string, r1 <-chan string, r2 error) *TestRunnerMockExpectation_Run {
	e.Expectation.Return(r0, r1, r2)
	return e
}

// OnWait starts building an expectation for the "Wait" method.
func (w *TestRunnerMock) OnWait() *TestRunnerMockExpectation_Wait {
	e := w.OnCall("Wait")
	return &TestRunnerMockExpectation_Wait{Expectation: e}
}

// TestRunnerMockExpectation_Wait is the typed expectation builder for the "Wait" method.
type TestRunnerMockExpectation_Wait struct{ *mock.Expectation }

// Return sets the fixed return values for this expectation.
func (e *TestRunnerMockExpectation_Wait) Return(r0 error) *TestRunnerMockExpectation_Wait {
	e.Expectation.Return(r0)
	return e
}
