// Code generated by glaciergen; DO NOT EDIT.

package commands

import (
	"github.com/nathanbrophy/glacier/cli"
)

func init() {
	if err := cli.Default.Register(&GlacierCmd{},
		cli.WithRoot(),
		cli.WithName("glacier"),
		cli.WithFlagEnv("OtelEndpoint", "OTEL_EXPORTER_OTLP_ENDPOINT"),
		cli.WithFlagShort("Quiet", 'q'),
		cli.WithFlagShort("Verbose", 'V'),
	); err != nil {
		panic(err)
	}
	if err := cli.Default.Register(&CompletionsCmd{},
		cli.WithName("completions"),
		cli.WithFlagChoices("Shell", "bash", "zsh", "fish", "pwsh"),
	); err != nil {
		panic(err)
	}
	if err := cli.Default.Register(&ExplainCmd{},
		cli.WithName("explain"),
	); err != nil {
		panic(err)
	}
	if err := cli.Default.Register(&GenerateCmd{},
		cli.WithName("generate"),
		cli.WithFlagValidate("Only", validateGeneratorList),
	); err != nil {
		panic(err)
	}
	if err := cli.Default.Register(&InitCmd{},
		cli.WithName("init"),
		cli.WithFlagChoices("Mascot", "polar_bear", "penguin", "owl", "fox", "otter", "raccoon"),
		cli.WithFlagChoices("Template", "library-only", "cli-app", "both"),
		cli.WithFlagShort("Yes", 'y'),
	); err != nil {
		panic(err)
	}
	if err := cli.Default.Register(&LintCmd{},
		cli.WithName("lint"),
		cli.WithFlagChoices("Format", "text", "json", "sarif"),
		cli.WithFlagChoices("Severity", "error", "warning", "info"),
	); err != nil {
		panic(err)
	}
	if err := cli.Default.Register(&NewCmd{},
		cli.WithName("new"),
	); err != nil {
		panic(err)
	}
	if err := cli.Default.Register(&NewCommandCmd{},
		cli.WithName("command"),
		cli.WithParent("new"),
	); err != nil {
		panic(err)
	}
	if err := cli.Default.Register(&NewOptionCmd{},
		cli.WithName("option"),
		cli.WithParent("new"),
	); err != nil {
		panic(err)
	}
	if err := cli.Default.Register(&NewPackageCmd{},
		cli.WithName("package"),
		cli.WithParent("new"),
	); err != nil {
		panic(err)
	}
	if err := cli.Default.Register(&TestCmd{},
		cli.WithName("test"),
		cli.WithFlagChoices("Format", "text", "junit", "sarif", "json"),
	); err != nil {
		panic(err)
	}
	if err := cli.Default.Register(&VersionCmd{},
		cli.WithName("version"),
	); err != nil {
		panic(err)
	}
	if err := cli.Default.Register(&VibeCmd{},
		cli.WithName("vibe"),
	); err != nil {
		panic(err)
	}
}
